### ISSUE TITLE
ERROR: is.subset: Error in .local(x, ...) : All item labels in x must be contained in 'itemLabels' or 'match'.

### ISSUE THREAD

**Issue by sjain777** [mhahsler/arules#2]
Hi, I get the following error from is.subset, example shown below: 

is.subset(as(list(c("salt","water"),c("pepper")), "transactions"), as(list(c("salt","water")), "transactions"))

_Error in .local(x, ...) : 
All item labels in x must be contained in 'itemLabels' or 'match'_.

The above error does not allow me to make predictions for NEW transactions, when I use the is.subset method as:

             rulesMatchLHS <- is.subset(rules@lhs, newtrans)

where "rules" is the model from "aprior" with target = "rules".  
I get the above error when the new data ("newtrans") has columns missing from the training data. 

Also, if I try using "subset" instead, I get the following error from transactions in newtrans that may contain newer items/values (columns/values) not seen in the training data. The error obtained is as follows:

Error in 
             subset(rules, subset = rules@lhs %in% LIST(newtrans[1])[[1]],  : 
Error in rules@lhs %in% LIST(newtrans[1])[[1]] : table contains an unknown item label

Could you please help fix the errors above? Or please point to how I could make predictions using new transactions that may contain new items or missing items from that seen in the training data. 

Thanks!

**Comment by mhahsler** [comment]
Hi sjain777,

The following is an item encoding error. 
Error in .local(x, ...) :
All item labels in x must be contained in 'itemLabels' or 'match'._

You get it because the two transaction sets that you create do not have the same encoding for items. You can see that the sets have a different number of items.

> t1 <- as(list(c("salt","water"),c("pepper")), "transactions")
> t1
transactions in sparse format with
 2 transactions (rows) and
 3 items (columns)

> t2 <- as(list(c("salt","water")), "transactions")
> t2
transactions in sparse format with
 1 transactions (rows) and
 2 items (columns)

I think your second example is caused by the same problem...

-Michael

So to make them comparable you need to do this
> t2_new <- recode(t2, match = t1)
> t2_new
transactions in sparse format with
 1 transactions (rows) and
 3 items (columns)

is.subset tries to do this internally, but fails for your data (I will fix that).
You can read up on item encoding in ?encode. The man page is somewhat hidden, but I will add some references in the other manual pages to make this easier to find. Now subset works as expected.

> is.subset(t1, t2_new)
             {salt,water}
{salt,water}         TRUE
{pepper}            FALSE

**Comment by sjain777** [comment]
Thanks for your quick response. I tried adding "recode" in my process as you advised above, but that failed too. I think, probably new labels (columns) in my test data are causing the problem this time. Here is the example to demonstrate the error: 

t1 <- as(list(c("salt","water"),c("pepper"), c("honey"), c("lemon")), "transactions")
t1
transactions in sparse format with
 4 transactions (rows) and
 5 items (columns)
 
t2 <- as(list(c("salt","sugar", "water")), "transactions") 
t2
transactions in sparse format with
 1 transactions (rows) and
 3 items (columns)

t2_new <- recode(t2, match = t1)
Error in .local(x, ...) : 
  All item labels in x must be contained in 'itemLabels' or 'match'.

Thanks for offering to work on a fix

- Supriya

**Comment by mhahsler** [comment]
You have in each set an item that is not in the other:

> t1 <- as(list(c("salt","water"),c("pepper"), c("honey"), c("lemon")), "transactions")
> t1
transactions in sparse format with
 4 transactions (rows) and
 5 items (columns)
> t2 <- as(list(c("salt","sugar", "water")), "transactions")
> t2
transactions in sparse format with
 1 transactions (rows) and
 3 items (columns)
> itemLabels(t1)
[1] "honey"  "lemon"  "pepper" "salt"   "water" 
> itemLabels(t2)
[1] "salt"  "sugar" "water"

So you need to recode them using all items (union)

> il <- union(itemLabels(t1), itemLabels(t2))
> t1 <- recode(t1, il)
> t2 <- recode(t2, il)

now subsetting will work

> is.subset(t1,t2)
             {salt,water,sugar}
{salt,water}               TRUE
{pepper}                  FALSE
{honey}                   FALSE
{lemon}                   FALSE

**Comment by sjain777** [comment]
Thanks again for your quick feedback. Doing the "union" and then "using "recode" as you suggested above worked! Thanks!
