### ISSUE TITLE
AScontrol : memopt, varying number of rules

### ISSUE THREAD

**Issue by anz000** [mhahsler/arules#25]
I get different number of rules when I turn it on/off. When memopt is TRUE, I usually get lesser rules. I am using minlen and maxlen, as well. Am I missing something? 

The new feature maxTime has anything to do with it?

**Comment by mhahsler** [comment]
This seems not to be a bug. If apriori warns and says that it runs out of time then `memopt=TRUE` will return potentially return fewer rules because it is slower to save memory usage. Set maxTime to a very large number to avoid this. In the next scheduled release (1.5-2), you will be able to disable the time limit by setting it to 0.
