### ISSUE TITLE
apriori() causes fatal crash of R when appearance of both LHS and RHS is constrained

### ISSUE THREAD

**Issue by cornejom** [mhahsler/arules#32]
Using arules 1.5-3 on R 3.3.3, running apriori() causes a fatal crash when the 'appearance' list specifies lhs and rhs items while default is "none".

See my [repository](https://github.com/cornejom/arules/tree/master) for reproducible example.

Code file baskets.R loads the data in assocs.RData, which consists of a data frame of market baskets and two character vectors specifying items to exclude from LHS and RHS when mining associations.
I provided three ready options for specifying the 'appearance' argument: constrain LHS, constrain RHS, constrain both.  R crashes when both sides are constrained.

**Comment by mhahsler** [comment]
Thank you for the bug report. Seems like the C code crashes if the same item is specified in more than one appearance location (you have several items specified in lhs and rhs). I have added code in the development version of arules that checks for this and throws an error instead of crashing R. You need to specify the items that can be in both sides under `both`).
