### ISSUE TITLE
Using base::write when called arules::write error

### ISSUE THREAD

**Issue by zx8754** [mhahsler/arules#46]
Maybe better error/warning output? See relevant post at SO:

https://stackoverflow.com/q/53185553/680068

I am guessing OP is passing a data.frame to `arules::write`, and `arules` is using `base::write` as input is not "transactions", maybe check input?

**Comment by mhahsler** [comment]
Thanks for the report. Unfortunately, arules cannot check the input and produce an error message since the R S4 method dispatching procedure directly calls the appropriate method (in the case of a  data.frame it calls directly write in base). The reason why you see that arules replaces the base write function is that in base write is not generic and arules just adds a generic function so a method for transactions can be added.
